---
title: "Orquídeas en Costa Rica"
output: html_document
---

# Carga de paquetes

```{r, message= FALSE, warning=FALSE}
library(sf)
library(raster)
library(dplyr)
library(spData)

library(leaflet)
library(plotly)
library(DT)
```


# Carga de datos 

```{r}
# *carga de los registros de presencia de las orquídeas*

familia_Orchidaceae <- st_read("https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv",
                              options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
   )


```


```{r}
# *carga de las áreas silvestres protegidas*

ASP <- st_read("https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/sinac/asp/asp-wgs84.geojson",
               quiet = TRUE)
```

```{r}
# **Asignación del sistema de coordenadas**

st_crs(ASP) = 4326
st_crs(familia_Orchidaceae) = 4326
```


# **1. Eliminar los registros con valor mayor a 1000 en los datos de presencia**

## Cantidad original: **29863**

```{r}
# *Descarte de datos con alta incertidumbre* 

familia_Orchidaceae <- 
  familia_Orchidaceae %>%
  filter(!is.na(coordinateUncertaintyInMeters) & coordinateUncertaintyInMeters < 1000) 


cat("Cantidad de registros después de descartar los de alta incertidumbre", nrow(familia_Orchidaceae))
```

## Cantidad de registros después de descartar los valores mayor a 1000 : **28406**


# **2. Elimiar los NA del campo *specie* en los registros de presencia**


```{r}
# *Descartar registros con species = NA

familia_Orchidaceae <- 
  familia_Orchidaceae %>%
  filter(!is.na(species))

cat("Cantidad de espacios luego de elimiar los NA:", nrow(familia_Orchidaceae))

```


# **3. Eliminar los valores del *Área Marina de Manejo* y *area marina protegida* del conjunto de datos ASP**


```{r}
ASP <-
  ASP %>%
  filter(!is.na(descripcio) & descripcio != "Area marina protegida")
```


```{r}
ASP <-
  ASP %>%
  filter(!is.na(descripcio) & descripcio != "Area Marina de Manejo")
```


# *Mapa Leaflet*


```{r}
# *Creación de conjunto de datos con la cantidad de registros por área protegida*

ASP_registros <-
  ASP %>%
  st_join(familia_Orchidaceae) %>%
  group_by(nombre_asp) %>%
  summarize(especies = n_distinct(species,na.rm = TRUE)) 
```

```{r}
# *Paleta de colores*

colores_registros <-
  colorNumeric(palette = "PiYG",
               domain = ASP_registros$especies,
               na.color = "transparent")


# *Paleta de colores*
colores_especies <-
  colorNumeric(palette = "PRGn",
               domain = ASP_registros$especies,
               na.color = "transparent")



# *Mapa Leaflet*

leaflet() %>%
  addTiles(group = "OSM") %>%
  addPolygons(
    data = ASP_registros,
    fillColor = ~ colores_especies(ASP_registros$especies),
    fillOpacity = 0.7,
    stroke = TRUE,
    color = "black",
    weight = 1,
    popup = paste(
      paste(
        "<strong>Provincia:</strong>",
        ASP_registros$nombre_asp
      ),
      paste(
        "<strong>Cantidad de especies:</strong>",
        ASP_registros$especies
        
      ),
      sep = '<br/>'
    ),
    group = "Provincias - especies"
  ) %>%
  addLayersControl(baseGroups = c("OSM"),
                   overlayGroups = c("Provincias - especies")) %>%
  addLegend(
    position = "bottomleft",
    pal = colores_especies,
    values = ASP_registros$especies,
    group = "Provincias - especies",
    title = "Cantidad de orquídeas por Área Silvestre Protegida")      





```








